services:
  - type: web
    name: pdf-chatbot-backend
    runtime: docker
    region: oregon
    plan: starter
    dockerfilePath: ./Dockerfile
    envVars:
      - key: USE_OLLAMA
        value: false
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 60
      - key: UPLOAD_CONCURRENCY
        value: 2
      - key: MAX_PDF_CHUNKS
        value: 200
      - key: USE_CUSTOM_DNS
        value: true
      - key: DNS_SERVERS
        value: 8.8.8.8,8.8.4.4,1.1.1.1
      - key: FORCE_IPV4
        value: true
      - key: GOOGLE_API_KEY
        sync: false
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: MONGODB_URI
        sync: false
